rootProject.name = "osrs-client-killer"

pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        mavenCentral()
    }
}

include(
    "deob-annotations",
    "signlink",
    "client",
    "playground",
    "plugin-playground"
)

startParameter.excludedTaskNames << ':playground:run'
