plugins {
    id 'java'
    id 'application'
}

application {
    mainClass = 'com.itspazaz.rt4.Playground'
}

version = '1.0.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 25
}

dependencies {
    implementation project(':client')
}
